//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 Copyright (c) 2024 Alexey Shulutkov <github@shulutkov.ru>

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/yandex-cloud/go-genproto/yandex/cloud/compute/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddConversionFunc((*ComputeInstance)(nil), (*v1.CreateInstanceRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComputeInstance_To_v1_CreateInstanceRequest(a.(*ComputeInstance), b.(*v1.CreateInstanceRequest), scope)
	}); err != nil {
		return err
	}
	return nil
}
